Repository IE-bbuda/mozi-backend, pull requests merged in 2025-07, with the labels that each got.

#14 Feature/search financial
  settings.gradle
  src/main/java/org/iebbuda/mozi/config/RootConfig.java
  src/main/java/org/iebbuda/mozi/config/ServletConfig.java
  src/main/java/org/iebbuda/mozi/controller/HomeController.java
  src/main/java/org/iebbuda/mozi/product/controller/DepositController.java
  src/main/java/org/iebbuda/mozi/product/controller/ProductController.java
  src/main/java/org/iebbuda/mozi/product/domain/DepositOption.java
  src/main/java/org/iebbuda/mozi/product/domain/DepositProduct.java
  src/main/java/org/iebbuda/mozi/product/domain/ProductVO.java
  src/main/java/org/iebbuda/mozi/product/domain/SavingOption.java
  src/main/java/org/iebbuda/mozi/product/domain/SavingProduct.java
  src/main/java/org/iebbuda/mozi/product/dto/.gitkeep
  src/main/java/org/iebbuda/mozi/product/dto/DepositApiResponse.java
  src/main/java/org/iebbuda/mozi/product/dto/DepositResponse.java
  src/main/java/org/iebbuda/mozi/product/dto/SavingApiResponse.java
  src/main/java/org/iebbuda/mozi/product/mapper/DepositMapper.java
  src/main/java/org/iebbuda/mozi/product/mapper/DepositOptionMapper.java
  src/main/java/org/iebbuda/mozi/product/mapper/DepositSyncMapper.java
  src/main/java/org/iebbuda/mozi/product/mapper/ProductMapper.java
  src/main/java/org/iebbuda/mozi/product/mapper/SavingSyncMapper.java
  src/main/java/org/iebbuda/mozi/product/scheduler/FinancialScheduler.java
  src/main/java/org/iebbuda/mozi/product/service/DepositQueryService.java
  src/main/java/org/iebbuda/mozi/product/service/DepositSyncService.java
  src/main/java/org/iebbuda/mozi/product/service/FinancialApiService.java
  src/main/java/org/iebbuda/mozi/product/service/ProductService.java
  src/main/java/org/iebbuda/mozi/product/service/ProductServiceImpl.java
  src/main/java/org/iebbuda/mozi/product/service/SavingSyncService.java
  src/main/resources/mybatis-config.xml
  src/main/resources/org/iebbuda/mozi/product/mapper/DepositMapper.xml
  src/main/resources/org/iebbuda/mozi/product/mapper/DepositOptionMapper.xml
  src/main/resources/org/iebbuda/mozi/product/mapper/DepositSyncMapper.xml
  src/main/resources/org/iebbuda/mozi/product/mapper/SavingSyncMapper.xml
Labels: enhancement

#17 feat: RootConfig.java파일 RestTemplate 빈 추가 및 xml파일 오류 수정
  .gitignore
  src/main/java/org/iebbuda/mozi/config/RootConfig.java
  src/main/resources/mybatis-config.xml
Labels: enhancement

#19 Feature/search financial
  src/main/resources/org/iebbuda/mozi/product/mapper/DepositMapper.xml
  src/main/resources/org/iebbuda/mozi/product/mapper/DepositOptionMapper.xml
  src/main/resources/org/iebbuda/mozi/product/mapper/DepositSyncMapper.xml
  src/main/resources/org/iebbuda/mozi/product/mapper/SavingSyncMapper.xml
Labels: bug

#24 Feature/user profile
  src/main/java/org/iebbuda/mozi/config/RootConfig.java
  src/main/java/org/iebbuda/mozi/config/ServletConfig.java
  src/main/java/org/iebbuda/mozi/profile/controller/ProfileController.java
  src/main/java/org/iebbuda/mozi/profile/domain/UserProfileVO.java
  src/main/java/org/iebbuda/mozi/profile/domain/enums/EducationLevel.java
  src/main/java/org/iebbuda/mozi/profile/domain/enums/EmploymentStatus.java
  src/main/java/org/iebbuda/mozi/profile/domain/enums/Major.java
  src/main/java/org/iebbuda/mozi/profile/domain/enums/MaritalStatus.java
  src/main/java/org/iebbuda/mozi/profile/domain/enums/Region.java
  src/main/java/org/iebbuda/mozi/profile/domain/enums/Specialty.java
  src/main/java/org/iebbuda/mozi/profile/dto/PersonalInfoDTO.java
  src/main/java/org/iebbuda/mozi/profile/dto/UserProfileInfoDTO.java
  src/main/java/org/iebbuda/mozi/profile/mapper/UserProfileMapper.java
  src/main/java/org/iebbuda/mozi/profile/service/ProfileService.java
  src/main/java/org/iebbuda/mozi/profile/service/ProfileServiceImpl.java
  src/main/java/org/iebbuda/mozi/profile/service/UserProfileService.java
  src/main/java/org/iebbuda/mozi/profile/service/UserProfileServiceImpl.java
  src/main/java/org/iebbuda/mozi/user/dto/response/MyPageResponseDTO.java
  src/main/resources/org/iebbuda/mozi/profile/mapper/UserProfileMapper.xml
Labels: enhancement

#31 feat: 탐색페이지 적금 상품 DTO/응답 서비스 구현
  src/main/java/org/iebbuda/mozi/domain/product/controller/SavingController.java
  src/main/java/org/iebbuda/mozi/domain/product/dto/SavingResponse.java
  src/main/java/org/iebbuda/mozi/domain/product/mapper/SavingMapper.java
  src/main/java/org/iebbuda/mozi/domain/product/mapper/SavingOptionMapper.java
  src/main/java/org/iebbuda/mozi/domain/product/service/SavingQueryService.java
  src/main/resources/org/iebbuda/mozi/domain/product/mapper/SavingMapper.xml
  src/main/resources/org/iebbuda/mozi/domain/product/mapper/SavingOptionMapper.xml
Labels: enhancement, ✨ Feature

#34 feat: GoalController 작업
  build.gradle
  src/main/java/org/iebbuda/mozi/config/JacksonConfig.java
  src/main/java/org/iebbuda/mozi/goal/controller/GoalController.java
  src/main/java/org/iebbuda/mozi/goal/dto/GoalDTO.java
Labels: ✨ Feature

#36 [Feature]goal 목표 관련 작업 완료 후 중간 브랜치 메인에 병합
  build.gradle
  src/main/java/org/iebbuda/mozi/config/JacksonConfig.java
  src/main/java/org/iebbuda/mozi/config/RootConfig.java
  src/main/java/org/iebbuda/mozi/config/ServletConfig.java
  src/main/java/org/iebbuda/mozi/domain/goal/controller/GoalController.java
  src/main/java/org/iebbuda/mozi/domain/goal/domain/GoalVO.java
  src/main/java/org/iebbuda/mozi/domain/goal/dto/.gitkeep
  src/main/java/org/iebbuda/mozi/domain/goal/dto/GoalDTO.java
  src/main/java/org/iebbuda/mozi/domain/goal/mapper/GoalMapper.java
  src/main/java/org/iebbuda/mozi/domain/goal/service/GoalService.java
  src/main/java/org/iebbuda/mozi/domain/goal/service/GoalServiceImpl.java
  src/main/resources/mybatis-config.xml
  src/main/resources/org/iebbuda/mozi/domain/goal/mapper/GoalMapper.xml
  src/test/java/org/iebbuda/mozi/config/RootConfigTest.java
  src/test/java/org/iebbuda/mozi/goal/controller/api-test.http
  src/test/java/org/iebbuda/mozi/goal/mapper/GoalMapperTest.java
  src/test/java/org/iebbuda/mozi/goal/service/GoalServiceImplTest.java
Labels: ✨ Feature
